### ISSUE TITLE
Create tabbed interface for FilterInputWidget

### ISSUE THREAD

**Issue by joeykleingers** [dream3d/DREAM3D#312]

**Comment by imikejackson** [comment]
Feedback on the new look:

+ move the tab bar to the top.
+ add a vertical spacer to each tab pane to remove some of the visual space that the tab looks like it takes up.
+ move the help to its own window and add a menu to the "Help" menu to display the help
+ Add a context click to the filter widget to show the filters help.
+ add a context menu to the filters in the "FilterListDockWidget" to show help for a specific filter.
+ add an obvious button to the actual FilterInputWidget that will display the help (Since we are removing the tab)

**Comment by joeykleingers** [comment]
Sub-issues that will be worked on in this issue:

A. DREAM3D should close all windows on quit.
B. Implement a right-click contextual menu for the Filter Parameter Widgets and Filter Library entries.
C. DREAM3D should not completely close on Mac unless Cmd + Q keystroke is given.
D. Read and write Json files to the file system.
E. Create a splitter subclass and create API that will instantiate separate instances of FilterInputWidget for each Filter Parameter Widget.  This will allow each filter widget to "remember" its settings, including what tab it was on last.
F. BUG - Selecting "Cancel" during a Dirty Document Check will still close the application.
G. Find a way to expand only one pane in a QSplitter.
H.  BUG - Signal/Slot related to loadPipeline is not hooked up correctly.

**Comment by imikejackson** [comment]
+ OS X: Auto quit when all windows are closed.
+ Change Help->Index to Help->DREAM3D Help
+ Update MacSplitterHandle to cover vertical
    + Change name to DREAM3DSplitterHandle
+ Mark document dirty when any filter parameter is changed.
+ Menus should disable at appropriate times
    + Ex: all windows closed, the pipeline menu is still active.

**Comment by imikejackson** [comment]
+ Document not marked as dirty when parameters are changed.
