### ISSUE TITLE
Import results of crystal plasticity simulations

### ISSUE THREAD

**Issue by colorblindy** [dream3d/DREAM3D#321]
Dear Developers: 

I have a text file obtained from crystal plasticity simulations that contains a table with coordinates of voxels and three Euler angles. I would like to analyze the results in Dream3D and I am wondering if there is a way to import these data directly to Dream3D. The grid is generally non regular so would I have to convert it to a regular one? 

I will be grateful for any feedback.

Thanks,
Marat

**Comment by imikejackson** [comment]
Which simulation codes created the output file?  You would probably have to convert the grid to a regular grid currently to import all the data.

**Comment by colorblindy** [comment]
It is a CPFEM code implemented in ABAQUS user subroutine UMAT. Output file is written by a custom Fortran snippet within the subroutine. I also have output files with similar format from DAMASK FFT simulations. 

Is there any filter in Dream3D that would allow conversion from unstructured grid to a regular grid (something like hex2square converter)? 

Thank you.

**Comment by sdonegan** [comment]
Currently, DREAM.3D does not have built in general functionality to convert a given unstructured grid to a regular grid.  There are some algorithms in development that can accomplish this task for specific unstructured grids.

What sort of grid is your data currently on?  Is it a mesh of tetrehedra, triangles, rectilinear (but unstructured), etc.?  This would help us figure out the easiest way to get the data in.  The current development version of DREAM.3D has explicit support for a wider array of unstructured grids, so this may be possible in the future.  However, it may require writing a filter to import your specific data format.

**Comment by colorblindy** [comment]
Orientations are calculated at integration points and written to a text file as a table also containing the coordinates (sample [here](https://dl.dropboxusercontent.com/u/19156272/cpfeOut_16x16x16.out)). In this case the information about the mesh is lost so that it is more like an ang file but with irregular xyz. If I transfer the data to a regular grid outside of Dream3D, what would be the best way to import it to Dream3D for analysis? 

Alternatively, I think I could add orientations to Abaqus output file and then write a vtk file (sample [here](https://dl.dropboxusercontent.com/u/19156272/cpfeOut_16x16x16.vtk), without orientations yet). In this case, it is a mesh of tetra or hexahedron elements. Maybe this way would be easier.

**Comment by sdonegan** [comment]
There are a couple of options that would work.  The current development version of DREAM.3D supports arbitrary point clouds, so you could read in the data as a bunch of points.  This would require writing a custom filter to read the data, and many filters do not work on point clouds, since they were explicitly optimized for structured rectilinear grids.

A more immediate option is to write the Euler angles as a binary file and use the filter Raw Binary Reader.  Raw Binary Reader assumes a structured rectilinear grid, so you would have to do that conversion yourself if you want to do any interpolations.  If you want to get the data in as-is, you could just write the Euler angles out to a binary file and then specify the (x,y,z) dimensions in the Raw Binary Reader filter.  This will implicitly convert the data to a structured grid.  This is probably the simplest option, since it would just require re-writing the Euler angles as a binary file and using an already existing filter.

**Comment by sdonegan** [comment]
The newest release of DREAM.3D includes a generic ASCII text importer with a corresponding wizard that allows a wide variety of data to be imported into DREAM.3D.  This filter should be used for importing data that does not have a dedicated reader.
