### ISSUE TITLE
Add Internationalization to widgets that need a decimal value

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#476]

**Comment by kglowins** [comment]
What's the status of this issue? I have problems, e.g., with specifying the "lambda" parameters for laplacian smoothing. In Poland (and probalby in some other countries in Europe), we use comma (",") instead of point (".") for decimal numbers, and in DREAM3D running on Polish Windows:
1. I am not able to input "." in the parameter field. Interestingly, I can just modify the prebuilt pipelines, and if I don't remove ".", it will work correctly.
2. I can input "," to have e.g., lambda = 0,2 but DREAM seems to read them as 0. Zero is also saved in HDF files.

**Comment by sdonegan** [comment]
Fixed with commit 98bdbaae5335d11767cdcb3312fbe1a6d25d042e.
